### ISSUE TITLE
Error in getDiagnostics source parsing issue

### ISSUE THREAD

**Issue by maiakaat** [Everlaw/nbts#42]
Hi

After installing and having a working plugin, for some reason, now whenever I start the IDE I get a code error, with a message "Error in getDiagnostics" showing next to the first line, for any typescript file.

I have tried installing a newer developer version of Netbeans, and removing and installing the plugin again, but have lost all the functionality of the plugin beyond basic file creation tools

The plugin was working (albeit a little bit slow to update errors when fixing causes) but after a few days it completely stopped.

A restart also didn't fix the issue

Using Netbeans IDE 8.1 on Windows 10 x64

**Comment by jeffrey-easyesi** [comment]
Does anything appear in the log files? I think in Windows the log is written to %APPDATA%\NetBeans\8.1\var\log\messages.log. In particular look for a log entry starting with
```
INFO [netbeanstypescript.TSService]: Exception in nodejs.eval
```

Also: does this happen on any project, or just files in one particular project?

**Comment by maiakaat** [comment]
Hi

Yes (this is from the nightly development version - but  the 8.1 release looks the same)

netbeanstypescript.TSService$ExceptionFromJS: TypeError: Cannot read property 'resolvedModule' of undefined
    at resolveModuleNamesWorker (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:32761:100)
    at processImportedModules (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:33360:35)
    at findSourceFile (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:33336:17)
    at processSourceFile (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:33263:27)
    at processRootFile (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:33186:13)
    at C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:32782:60
    at Object.forEach (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:88:30)
    at Object.createProgram (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:32782:16)
    at synchronizeHostData (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:40029:33)
    at Object.getProgram (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:40082:13)
	at netbeanstypescript.TSService$NodeJSProcess.eval(TSService.java:183)
[catch] at netbeanstypescript.TSService$ProgramData.call(TSService.java:221)
	at netbeanstypescript.TSService$2.run(TSService.java:358)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
INFO [netbeanstypescript.TSService]: Exception in nodejs.eval
netbeanstypescript.TSService$ExceptionFromJS: TypeError: Cannot read property 'getSourceFile' of undefined
    at Program.fileInProject (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:44537:43)
    at Program.getDiagnostics (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:44541:19)
    at eval (eval at <anonymous> (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:44926:37), <anonymous>:1:4)
    at Interface.<anonymous> (C:\Users\Jodi\AppData\Roaming\NetBeans\dev\nbts-services.js:44926:32)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
	at netbeanstypescript.TSService$NodeJSProcess.eval(TSService.java:183)
[catch] at netbeanstypescript.TSService$ProgramData.call(TSService.java:221)
	at netbeanstypescript.TSService$2.run(TSService.java:358)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
INFO [null]: Last record repeated more than 10 times, further logs of this record are ignored until the log record changes.
INFO [null]: Last record repeated 1416 times in total.

**Comment by maiakaat** [comment]
It has happened on three projects that were working fine with the plugin. 

code was largely from a Manning MEAP on Angular2 and typescript, mixed with standard processes for creating a node.js project. I'm just getting started learning Angular2

One was the provided source folder, one was built from scratch, but using identical code to this folder, and one was another tutorial for creating a seed app, but with tasks performed within Netbeans tooling by me were suitable.

I opened a new project (via existing sources, using the node.js application type) and added to tsconfig.json file as needed - and it didn't happen, and is working fine, just like the others did initially. 

Is it something I am doing wrong?

**Comment by jeffrey-easyesi** [comment]
In the broken projects' tsconfig.json file, what is the setting for `moduleResolution`? (If present, it should be "node" or "classic".)

**Comment by maiakaat** [comment]
Hi

It was commonjs, I changed the settings to those for some reason, (from what I thought was an authoritative source of information)

Although it works with commonjs when first created, and then stops working later

It's started working again now, thanks lots

This was the settings file used, which was not the original one I used

{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "commonjs",
    "experimentalDecorators": true,
    "noImplicitAny": true
  }
}

**Comment by maiakaat** [comment]
I think I'll send feedback to the Author about how the tsconfig.json settings don't work well with this plugin in Netbeans, as he doesn't discuss the nature of configuration early on, and I'm guessing Angular2 and Java are a common combination (It came from the Author himself)

The modified file is now

{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "system",
    "moduleResolution": "node",
    "target": "ES5",
    "noEmit": true
  },
  "exclude": [
    "node_modules"
  ]
}

Typescript configuration files are now on my reading list
